### ISSUE TITLE
Replace deprecated React.createClass

### ISSUE THREAD

**Issue by hugoabonizio** [nobitagit/react-material-floating-button#25]
Due to the deprecation of ```React.createClass``` this warning is raised:

```Warning: MainButton: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.```

I'm opening this issue to suggest to follow one of this plans: change the definitions of the components (Menu, MainButton and ChildButton) using plain JS classes, or use the create-react-class module. The most straightforward solution is just use the create-react-class module.

WDYT @nobitagit?

(related #24)

**Comment by nobitagit** [comment]
Thanks for this issue.

It looks like using `react-create-class` module would be a quick fix but would also mean reopening this very issue as soon as v16 is out. So, my preference would be to just convert it to using classes straight away. Would you be able to set up a PR for this?

**Comment by hugoabonizio** [comment]
I completely agree with you. Done #26.

**Comment by nobitagit** [comment]
Closed via #26 and published as v0.6.0

**Comment by hugoabonizio** [comment]
Thanks! :smile:
