### ISSUE TITLE
Accept inline styles

### ISSUE THREAD

**Issue by edcolcode** [nobitagit/react-material-floating-button#27]
Hi, 

I'm using your awesome component in a project. I tried to pass inline styles to the main and child buttons but I realized that them are not taking that in count the style property. I made some changes in the component and now is taking the style property too. I think that this functionality can help others so is a good idea to include this on master branch.

Thanks & regards.

**Comment by nobitagit** [comment]
Merged via https://github.com/nobitagit/react-material-floating-button/commit/2c9a0792e4278bc1085161f291f549d242e5822d
