### ISSUE TITLE
Include SCSS in npm install

### ISSUE THREAD

**Issue by yeojz** [nobitagit/react-material-floating-button#4]
It would be good to also include the SCSS file when we do `npm install react-mfb`. 
This would allow us to do an `@import` in our own application scss, and at the same time tweak the variables.

**Comment by phated** [comment]
Published as 0.2.1

**Comment by vanoode** [comment]
@phated mfb.scss try to:

`@import "_/_slidein";
@import "_/_slidein-spring";
@import "_/_zoomin";
@import "_/_fountain";`

But its not present in package.

**Comment by rzymek** [comment]
Continued in issue #31 and pull request #32
