### ISSUE TITLE
Integration with Google Material Icons

### ISSUE THREAD

**Issue by adrianha** [nobitagit/react-material-floating-button#7]
Are you willing to integrate the icon using Google Material Icons? if you are, i will pull request to merge the enhancement..

**Comment by adrianha** [comment]
any thought @nobitagit @phated ?

**Comment by nobitagit** [comment]
Sure, that's fine for me.

**Comment by DonovanCharpin** [comment]
It would be really nice! Any update on that?

**Comment by MaxInMoon** [comment]
Any news?
